basepath = 'D:\Workshop_test_data\Raw_data';
excelFile = 'D:\Workshop_test_data\Channel_map_xml_cheat_sheat\channel_map.xlsx';
genXML_path = 'D:\Workshop_test_data\Channel_map_xml_cheat_sheat';

channelGroups = excel2xml(excelFile, ...
    'basepath', basepath, ...
    'samplingRate', 20000, ...
    'genXML_path', genXML_path);
