# Phy params.py for Dec 3 haptic mouse session.
# Generated by analysis/prepare_spike_sorting_dec3.py.
# This points to the raw Intan amplifier.dat. Do not edit raw data in place.

dat_path = r"Haptic_Stim_session1_251203_143031/amplifier.dat"
n_channels_dat = 128
dtype = "int16"
offset = 0
sample_rate = 20000.0
hp_filtered = False

# Channel map and bad-channel decisions are in this folder.
# Anatomy labels are intentionally not assigned yet.
