#!/usr/bin/env python3
"""Prepare Dec 3 spike-sorting metadata without modifying raw amplifier.dat."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.io import savemat


ANALYSIS_GROUPS = {
    "Group 0-31": list(range(0, 32)),
    "Group 32-63": list(range(32, 64)),
    "Group 64-95": list(range(64, 96)),
    "Group 96-127": list(range(96, 128)),
}

DEFAULT_RAW_DAT = Path("Haptic_Stim_session1_251203_143031/amplifier.dat")


def channel_group(channel: int) -> str:
    for group, channels in ANALYSIS_GROUPS.items():
        if channel in channels:
            return group
    raise ValueError(f"Unknown channel {channel}")


def physical_shank(channel: int) -> str:
    return "Physical Shank A (0-63)" if channel < 64 else "Physical Shank B (64-127)"


def provisional_geometry(channel: int) -> tuple[float, float, int]:
    """Return provisional x/y/kcoords for setup, not final anatomical geometry."""
    shank = 0 if channel < 64 else 1
    within = channel % 64
    x = float(shank * 250)
    y = float(within * 20)
    kcoord = shank + 1
    return x, y, kcoord


def write_params_py(output: Path, raw_dat: Path, n_channels: int, sample_rate_hz: float) -> None:
    text = f"""# Phy params.py for Dec 3 haptic mouse session.
# Generated by analysis/prepare_spike_sorting_dec3.py.
# This points to the raw Intan amplifier.dat. Do not edit raw data in place.

dat_path = r"{raw_dat}"
n_channels_dat = {n_channels}
dtype = "int16"
offset = 0
sample_rate = {sample_rate_hz}
hp_filtered = False

# Channel map and bad-channel decisions are in this folder.
# Anatomy labels are intentionally not assigned yet.
"""
    output.write_text(text)


def write_readme(output: Path, config: dict, raw_dat: Path) -> None:
    bad = config["channels"]["definite_bad_channels"]
    text = f"""# Dec 3 Spike-Sorting Prep

This folder contains metadata for preparing spike sorting for:

`{raw_dat}`

The raw `amplifier.dat` is **not modified** by this prep step.

## Current Decisions

- Channel count: `128`
- Sample rate: `20000 Hz`
- Bad channels treated as confirmed for this analysis pass:
  `{bad}`
- Phantom channels removed/ignored: `128-255`
- Trial timing source: `analysis/outputs/dec3/dec3_condition_sequence.csv`
- TTL source: `digitalin.dat` bit 7, used as QC, not the sole trial label source.

## Files

- `channel_metadata.csv`: one row per channel, including bad/connected flags.
- `bad_channels.txt`: confirmed bad channels, one per line.
- `good_channels.txt`: connected channels, one per line.
- `kilosort_channel_map.mat`: MATLAB channel map for Kilosort-style tools.
- `phy_params.py`: minimal Phy params file pointing at raw `amplifier.dat`.
- `stim_artifact_intervals.csv`: onset/offset windows to inspect or optionally exclude.
- `trial_windows.csv`: ON/OFF windows for all 1200 trials.
- `spike_sorting_plan.md`: practical next commands and caveats.

## Important Caveat

The `kilosort_channel_map.mat` uses provisional geometry:

- channels `0-63`: physical shank A
- channels `64-127`: physical shank B
- shank spacing: `250 um`
- vertical spacing placeholder: `20 um`

This is enough to start tool setup and sanity checks, but the exact Cambridge
NeuroTech `H12_2` contact geometry/channel order should be substituted before
final spike sorting claims.
"""
    output.write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=Path("analysis/final_preprocessing_dec3.json"))
    parser.add_argument("--sequence", type=Path, default=Path("analysis/outputs/dec3/dec3_condition_sequence.csv"))
    parser.add_argument("--output-dir", type=Path, default=Path("analysis/outputs/dec3/spike_sorting_prep"))
    parser.add_argument("--raw-dat", type=Path, default=DEFAULT_RAW_DAT)
    args = parser.parse_args()

    config = json.loads(args.config.read_text())
    n_channels = 128
    sample_rate_hz = 20000.0
    raw_dat = args.raw_dat
    bad_channels = set(int(ch) for ch in config["channels"]["definite_bad_channels"])

    args.output_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for channel in range(n_channels):
        x, y, kcoord = provisional_geometry(channel)
        rows.append(
            {
                "channel": channel,
                "intan_label": f"A-{channel:03d}",
                "analysis_group": channel_group(channel),
                "physical_shank": physical_shank(channel),
                "is_bad": channel in bad_channels,
                "connected": channel not in bad_channels,
                "x_um_provisional": x,
                "y_um_provisional": y,
                "kcoord_provisional": kcoord,
            }
        )
    channels = pd.DataFrame(rows)
    channels.to_csv(args.output_dir / "channel_metadata.csv", index=False)

    good = channels.loc[channels["connected"], "channel"].to_numpy(dtype=np.int32)
    bad = channels.loc[channels["is_bad"], "channel"].to_numpy(dtype=np.int32)
    np.savetxt(args.output_dir / "good_channels.txt", good, fmt="%d")
    np.savetxt(args.output_dir / "bad_channels.txt", bad, fmt="%d")
    np.save(args.output_dir / "good_channels.npy", good)
    np.save(args.output_dir / "bad_channels.npy", bad)

    chan_map0 = np.arange(n_channels, dtype=np.int32)
    chan_map1 = chan_map0 + 1
    connected = channels["connected"].to_numpy(dtype=bool)
    xcoords = channels["x_um_provisional"].to_numpy(dtype=float)
    ycoords = channels["y_um_provisional"].to_numpy(dtype=float)
    kcoords = channels["kcoord_provisional"].to_numpy(dtype=np.int32)
    savemat(
        args.output_dir / "kilosort_channel_map.mat",
        {
            "chanMap": chan_map1.reshape(-1, 1),
            "chanMap0ind": chan_map0.reshape(-1, 1),
            "connected": connected.reshape(-1, 1),
            "xcoords": xcoords.reshape(-1, 1),
            "ycoords": ycoords.reshape(-1, 1),
            "kcoords": kcoords.reshape(-1, 1),
            "fs": sample_rate_hz,
        },
    )

    sequence = pd.read_csv(args.sequence)
    trial_windows = sequence[
        [
            "trial_number",
            "condition",
            "amplitude",
            "freq",
            "recording_start_time_s",
            "recording_end_time_s",
            "on_time_s",
            "off_time_s",
        ]
    ].copy()
    trial_windows["on_start_s"] = trial_windows["recording_start_time_s"]
    trial_windows["on_end_s"] = trial_windows["recording_end_time_s"]
    trial_windows["off_start_s"] = trial_windows["recording_end_time_s"]
    trial_windows["off_end_s"] = trial_windows["recording_end_time_s"] + trial_windows["off_time_s"]
    trial_windows.to_csv(args.output_dir / "trial_windows.csv", index=False)

    intervals = []
    for row in trial_windows.itertuples(index=False):
        intervals.append(
            {
                "trial_number": row.trial_number,
                "condition": row.condition,
                "event": "stim_onset_margin",
                "start_s": max(0.0, row.on_start_s - 0.05),
                "end_s": row.on_start_s + 0.10,
            }
        )
        intervals.append(
            {
                "trial_number": row.trial_number,
                "condition": row.condition,
                "event": "stim_offset_margin",
                "start_s": row.on_end_s - 0.10,
                "end_s": row.on_end_s + 0.20,
            }
        )
    pd.DataFrame(intervals).to_csv(args.output_dir / "stim_artifact_intervals.csv", index=False)

    write_params_py(args.output_dir / "phy_params.py", raw_dat, n_channels, sample_rate_hz)
    write_readme(args.output_dir / "README.md", config, raw_dat)

    plan = f"""# Spike Sorting Plan

## 1. Install Sorting Tools

No spike sorting package was installed in the current Python environment when
this prep was generated. Recommended options:

```bash
pip install spikeinterface probeinterface phylib
```

For Kilosort, install the version you plan to use separately, preferably in a
dedicated environment with GPU support.

## 2. Use Raw Data, Do Not Overwrite

Raw data:

`{raw_dat}`

Keep this file immutable. Let the sorting tool do filtering/CAR, or write any
derived binary to a separate output folder.

## 3. Bad Channels

Use `bad_channels.txt` / `channel_metadata.csv`.

Confirmed current-pass bad channels:

`{sorted(bad_channels)}`

## 4. Artifact Windows

Use `stim_artifact_intervals.csv` to inspect stimulation onset/offset artifacts.
Do not delete these intervals blindly; first decide whether the sorter should
ignore, annotate, or tolerate them.

## 5. Geometry Caveat

`kilosort_channel_map.mat` has provisional two-shank geometry. Replace it with
the exact Cambridge NeuroTech H12_2 map before final sorting if possible.

## 6. After Sorting

After Kilosort/Phy curation, align units to:

- ON: `0-3 s`
- OFF: `3-6 s`
- early/middle/late repeats
- condition: amplitude x frequency

The LFP result to test in spikes is:

`180/26` has sustained-plus-OFF broadband response, and `250/26` adapts downward.
"""
    (args.output_dir / "spike_sorting_plan.md").write_text(plan)

    summary = {
        "output_dir": str(args.output_dir),
        "raw_dat": str(raw_dat),
        "n_channels": n_channels,
        "sample_rate_hz": sample_rate_hz,
        "bad_channels": sorted(bad_channels),
        "good_channel_count": int(len(good)),
        "channel_map": str(args.output_dir / "kilosort_channel_map.mat"),
        "geometry_status": "provisional_placeholder_until_exact_H12_2_map_is_confirmed",
    }
    (args.output_dir / "spike_sorting_prep_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
